language: node_js
node_js:
  - 14.15.4
  - node
dist: bionic
sudo: required

branches:
  only:
    - develop
    - master

before_script:
  - npm i -g gatsby-cli
  - npm i

script:
  # TODO: Implement tests and run suitable npm script here. 
  # eg. - npm run test
  - npm run build

before_deploy: "echo 'Ready to deploy..'"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  keep-history: true
  target-branch: staging
  on:
    branch: develop
