language: node_js
node_js:
  - 12.13.0
  - node
dist: xenial
sudo: required

branches:
  only:
    - develop

before_script:
  - npm i -g gatsby
  - npm i

script:
  # TODO: Implement tests and run suitable npm script here.
  # eg. - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: develop
